services:

  nginx:
    image: nginx:alpine
    container_name: 3gdeco-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - 3gdeco-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: 3gdeco-backend-dev
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - 3gdeco-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: 3gdeco-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - 3gdeco-network

  mysql:
    image: mysql:8.4
    container_name: 3gdeco-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 3gdeco
      MYSQL_USER: 3gdeco
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 3gdeco-network

volumes:
  mysql_data:

networks:
  3gdeco-network:
    driver: bridge